#!/usr/bin/env python3

import sys

try:
	# CAPITOL es refereix al numero que li entrem
	CAPITOL = sys.argv[1]
	# TEMA es refereix al CAPITOL.X.Y.Z que li passa prova.py
	TEMA = sys.argv[2]
	# PART es refereix a si es la PART1, la 2, la 3 o la 4
	PART = sys.argv[3]
except IndexError:
	print("\nERROR\n")
	exit()

FitxerOrigen = open("/home/jacquard/Documents/UOC/Latex/" + PART + "/capitol" + CAPITOL + "/DadesBrut/" + TEMA, "r")
#FitxerOrigen2 = open("/home/jacquard/sed.txt", "r")
FitxerFinal = open("/home/jacquard/final_latex.txt", "w")
FitxerFinal2 = open("/home/jacquard/Documents/UOC/Latex/" + PART + "/capitol" + CAPITOL + "/DadesBrut/" + CAPITOL + ".tex", "a")

fitxer = FitxerOrigen.read()

fitxer = fitxer.replace("<h1>","\\subsubsection{")
fitxer = fitxer.replace("</h1>\n        <div>\n<p>","}\n\\indent ")
fitxer = fitxer.replace("</h1>\n","}\n")
fitxer = fitxer.replace("<p>\n<b>","\\\\[0.1cm]\n\\textbf{");
fitxer = fitxer.replace("Nota:</b>","Nota}:")
fitxer = fitxer.replace(":</b>\n</p>\n<p></p>\n<p>\n</p>\n<ul>",":\n\\begin{itemize}")
fitxer = fitxer.replace(":</p>\n<p></p>\n<p>\n<ul>\n<li>",":\n\n\\begin{itemize}\n\\item ")
fitxer = fitxer.replace(".</p>\n<p></p>\n<p>\n<ul>\n<li>",".\n\n\\begin{itemize}\n\\item\n\t")
fitxer = fitxer.replace(". </p>\n<p></p>\n<p>\n<ul>\n<li>",".\n\n\\begin{itemize}\n\\item\n\t")
fitxer = fitxer.replace(":</p>\n<p>\n<ul>\n<li>",":\n\n\\begin{itemize}\n\\item\n\t")
fitxer = fitxer.replace(":</b>\n</p>\n<p>\n<ul>\n<li>",":\n\n\\begin{itemize}\n\\item\n\t")
fitxer = fitxer.replace(": </b>\n</p>\n<p>\n<ul>\n<li>",":\n\n\\begin{itemize}\n\\item\n\t")
fitxer = fitxer.replace("</b>\n</p>\n<p></p>\n<p>","}\n\\\\[0.3cm]\n\\indent ")
fitxer = fitxer.replace("</b>\n</p>\n<p>","}\n\\\\[0.3cm]\n\\indent ")
fitxer = fitxer.replace(".</p>\n<p></p>\n<p>\n</p>\n<ul>",".\n\n\\begin{itemize}")
fitxer = fitxer.replace(". </p>\n<p></p>\n<p>\n</p>\n<ul>",". \n\n\\begin{itemize}")
fitxer = fitxer.replace(":</p>\n<p></p>\n<p>\n</p>\n<ul>",":\n\n\\begin{itemize}")
fitxer = fitxer.replace(": </p>\n<p></p>\n<p>\n</p>\n<ul>",":\n\n\\begin{itemize}")
fitxer = fitxer.replace(".</p>\n<p>\n</p>\n<ul>",".\n\n\\begin{itemize}")
fitxer = fitxer.replace(". </p>\n<p>\n</p>\n<ul>",".\n\n\\begin{itemize}")
fitxer = fitxer.replace(":</p>\n<p>\n</p>\n<ul>",":\n\n\\begin{itemize}")
fitxer = fitxer.replace(": </p>\n<p>\n</p>\n<ul>",":\n\n\\begin{itemize}")
fitxer = fitxer.replace(": </p>\n<p>\n<ul>\n<li>",":\n\n\\begin{itemize}\n\\item ")
fitxer = fitxer.replace(": </p>\n<p></p>\n<p>\n<ul>\n<li>","\n\n\\begin{itemize}\n\\item ")
fitxer = fitxer.replace("?</p>\n<p></p>\n<p>\n</p>\n<ul>","\n\n\\begin{itemize}")
fitxer = fitxer.replace("? </p>\n<p></p>\n<p>\n</p>\n<ul>","\n\n\\begin{itemize}")
fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p></p>\n<p>\n<a ","\n\\end{itemize}\n\n\\")
fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p></p>\n<p>","\n\\end{itemize}\n\n\\indent ")
fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p></p>","\n\\end{itemize}\n\n\\indent ")
fitxer = fitxer.replace("</li>\n</ul>\n</p>\n<p></p>\n<p>","\n\\end{itemize}\n\n\\indent ")
fitxer = fitxer.replace("</li>\n</ul>\n</p>\n<p></p>","\n\\end{itemize}\n\n\\indent ")
fitxer = fitxer.replace(".</p>\n<p></p>\n<p>","\n\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace(". </p>\n<p></p>\n<p>","\n\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace(":</p>\n<p></p>\n<p>","\n\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace(": </p>\n<p></p>\n<p>","\n\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace("</p>\n<p></p>\n<p>","\n\\\\[0.1cm]\n\indent ")
#fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p></p>\n<p>\n<a ","\n\\end{itemize}\n\n\\")
#fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p></p>\n<p>","\n\\end{itemize}\n\n\\indent ")
fitxer = fitxer.replace("</li>\n</ul>\n<p></p>\n<p>\n</p><ul>","")
fitxer = fitxer.replace("</p>\n<p>","\n\\\\[0.1cm]\n\\indent ")
fitxer = fitxer.replace("<p>\n","")
fitxer = fitxer.replace("<p></p>\n","")
fitxer = fitxer.replace("</p><ul>\n","")
fitxer = fitxer.replace("</ul>\n","")
fitxer = fitxer.replace(":</b>","</b>:")
fitxer = fitxer.replace("<i>","\\textit{")
fitxer = fitxer.replace("</i>","}")
#fitxer = fitxer.replace(": </p>\n","\n\\begin{itemize}\n")
#fitxer = fitxer.replace(":\n</p>","\n\\begin{itemize}\n")
#fitxer = fitxer.replace(":</p>\n",":\n\\begin{itemize}\n")
#fitxer = fitxer.replace("?</p>\n","?\n\\begin{itemize}\n")
fitxer = fitxer.replace("<li>","\\item\n\t")
fitxer = fitxer.replace("<span class=\"cmd\">","")
fitxer = fitxer.replace("</span>","")
fitxer = fitxer.replace("<b>","\\textbf{")
fitxer = fitxer.replace("</b>","}")
#fitxer = fitxer.replace("</li>\n<p>","\n\end{itemize}\n~\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace("</li>","")
#fitxer = fitxer.replace("<p>","\\\\[0.1cm]\n\indent ")
fitxer = fitxer.replace("</p>","")
fitxer = fitxer.replace("<a href=\"","\\href{")
fitxer = fitxer.replace("\" target=\"","}")
fitxer = fitxer.replace("_blank\">","{")
fitxer = fitxer.replace("_","\\_")
fitxer = fitxer.replace("&","\&")
fitxer = fitxer.replace("</a>","}\n\\\\[0.1cm]")
fitxer = fitxer.replace("&nbsp;"," ")
fitxer = fitxer.replace("\xa0"," ")
fitxer = fitxer.replace("<foto>", "\\begin{figure}[h!]\n\t\\begin{center}\n\t\t\includegraphics[scale=0.8]{" + PART + "/capitol10/imatges/")
fitxer = fitxer.replace("<final>","}\n\t\\end{center}\t")
fitxer = fitxer.replace("<caption>","\\caption{")
#fitxer = fitxer.replace("</caption>","}")
fitxer = fitxer.replace("</foto>", "\\end{figure}\n~\\\\[0.1cm]\n")
fitxer = fitxer.replace("#","\\#")
fitxer = fitxer.replace("^","\\^")
fitxer = fitxer.replace("%","\\%")
fitxer = fitxer.replace("<p></p>\n","")
fitxer = fitxer.replace("../../files","https://static-course-assets.s3.amazonaws.com/RSE503/es/course/files")
fitxer = fitxer.replace("siguientes objetivos:","siguientes objetivos:}")
fitxer = fitxer.replace("\n\n\\\\[0.1cm]\n\\indent \n<ul>\n\\item","\n\\item")

FitxerFinal.write(fitxer)
FitxerFinal2.write(fitxer)

FitxerFinal.close()
FitxerFinal2.close()

FitxerOrigen.close()
#FitxerOrigen2.close()
